name: Build and test

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - develop
      - test-zx-312
  schedule:
    # 03:00 every Saturday morning
    - cron: '0 3 * * 6'
  workflow_dispatch: {}

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  check_changes:
    name: Check tket library version
    runs-on: ubuntu-22.04
    outputs:
      tket_or_workflow_changed: ${{ steps.filter.outputs.tket_or_workflow }}
      tket_changed: ${{ steps.filter.outputs.tket }}
      doxyfile_or_workflow_changed: ${{ steps.filter.outputs.doxyfile_or_workflow }}
      pytket_or_workflow_changed: ${{ steps.filter.outputs.pytket_or_workflow }}
      tket_ver: ${{ steps.tket_ver.outputs.tket_ver }}
      tket_package_exists: ${{ steps.tket_package_exists.outputs.tket_package_exists }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - uses: dorny/paths-filter@v3.0.0
      id: filter
      with:
        base: ${{ github.ref }}
        filters: |
          tket:
            - '{tket/src/**,tket/include/**,tket/conanfile.py,tket/CMakeLists.txt,tket/cmake/**,tket/test/**,tket/proptest/**}'
          tket_or_workflow:
            - '{tket/src/**,tket/include/**,tket/conanfile.py,tket/CMakeLists.txt,tket/cmake/**,tket/test/**,tket/proptest/**}'
            - '.github/workflows/build_and_test.yml'
          doxyfile_or_workflow:
            - '{tket/Doxyfile}'
            - '.github/workflows/build_and_test.yml'
          pytket_or_workflow:
            - 'pytket/**'
            - '.github/workflows/build_and_test.yml'
    - name: Install conan
      uses: turtlebrowser/get-conan@v1.2
    - name: parse version from conanfile
      id: tket_ver
      run: |
        tket_ver=$(conan inspect tket/conanfile.py | grep "^version: " | awk '{print $2}')
        echo "tket_ver=${tket_ver}" >> $GITHUB_OUTPUT
    - name: See if version exists on remote
      id: test_package_exists
      run: |
        conan remote add tket-libs https://quantinuumsw.jfrog.io/artifactory/api/conan/tket1-libs --index 0
        tket_package_exists=`conan search -r tket-libs "tket/${{ steps.tket_ver.outputs.tket_ver }}@tket/stable" | grep "not found" > /dev/null 2>&1 && echo false || echo true`
        echo "tket_package_exists=${tket_package_exists}" >> $GITHUB_OUTPUT
    - name: Check tket version bump
      if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'develop' && steps.filter.outputs.tket == 'true' && steps.test_package_exists.outputs.tket_package_exists == 'true'
      run: exit 1

  build_test_pytket_ubuntu:
    name: Build and test pytket (ubuntu)
    needs: check_changes
    if: needs.check_changes.outputs.tket_or_workflow_changed == 'true' || needs.check_changes.outputs.pytket_or_workflow_changed == 'true'
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - name: Install conan
      uses: turtlebrowser/get-conan@v1.2
    - name: Set up conan
      run: |
        conan profile detect
        DEFAULT_PROFILE_PATH=`conan profile path default`
        PROFILE_PATH=./conan-profiles/ubuntu-22.04
        diff ${DEFAULT_PROFILE_PATH} ${PROFILE_PATH} || true
        cp ${PROFILE_PATH} ${DEFAULT_PROFILE_PATH}
        conan remote add tket-libs https://quantinuumsw.jfrog.io/artifactory/api/conan/tket1-libs --index 0
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: tket-dynamic-ubuntu-22.04
    - name: further ccache config
      run: |
        ccache --set-config base_dir=${HOME}
        ccache --set-config compiler_check=content
        ccache -p
    - name: Build tket
      if: needs.check_changes.outputs.tket_changed == 'true'
      run: conan create tket --user tket --channel stable -o boost/*:header_only=True -o tklog/*:shared=True -o tket/*:shared=True -tf ""
    - name: Install tket
      if: needs.check_changes.outputs.tket_changed != 'true'
      run: conan install --requires tket/${{ needs.check_changes.outputs.tket_ver }}@tket/stable -o boost/*:header_only=True -o tklog/*:shared=True -o tket/*:shared=True
    - name: check that version is consistent
      if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
      run: ./.github/workflows/check-tket-reqs  ${{ needs.check_changes.outputs.tket_ver }}
    - name: Install pytket requirements
      run: |
        conan create recipes/pybind11
        conan create recipes/pybind11_json/all --version 0.2.13
    - name: Set up Python (pull request)
      if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Set up Python (push)
      if: github.event_name == 'push'
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Set up Python (schedule)
      if: github.event_name == 'schedule'
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Build pytket
      run: |
        cd pytket
        pip install -e .[ZX] -v
    - name: Run doctests
      run: |
        cd pytket
        pip install pytest
        pytest --doctest-modules pytket
    - name: Test pytket with coverage
      if: github.event_name == 'pull_request' || github.event_name == 'push' || github.event_name == 'workflow_dispatch'
      run: |
        cd pytket/tests
        pip install -r requirements.txt
        pytest --ignore=simulator/ --hypothesis-seed=1 --cov=../pytket --cov-branch --cov-report=html --cov-report=xml:htmlcov/cov.xml
    - name: Test pytket
      if: github.event_name != 'pull_request' || github.event_name == 'workflow_dispatch'
      run: |
        cd pytket/tests
        pip install -r requirements.txt
        pytest --ignore=simulator/
    - name: Test building docs
      if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
      timeout-minutes: 20
      run: |
        pip install -r pytket/docs/requirements.txt
        ./.github/workflows/build-docs
    - name: Upload artefact
      if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
      uses: actions/upload-artifact@v4
      with:
        name: pytket_docs
        path: pytket/docs/build/html/
    - name: Upload pytket coverage artefact
      if: github.event_name == 'pull_request' || github.event_name == 'push' || github.event_name == 'workflow_dispatch'
      uses: actions/upload-artifact@v4
      with:
        name: pytket_test_coverage
        path: pytket/tests/htmlcov
    - name: Upload package
      if: github.event_name == 'push' && github.ref == 'refs/heads/develop' && needs.check_changes.outputs.tket_changed == 'true'
      run: |
        conan remote login -p ${{ secrets.JFROG_ARTIFACTORY_TOKEN_3 }} tket-libs ${{ secrets.JFROG_ARTIFACTORY_USER_3 }}
        conan upload tket/${{ needs.check_changes.outputs.tket_ver }}@tket/stable -r=tket-libs
