name: Release

on:
  release:
    types:
      - created
  push:
    branches:
      - 'wheel/**'
      - test-delocate

jobs:
  build_macos_arm64_wheels:
    name: Build macos arm64 wheels
    runs-on: macos-14
    strategy:
      matrix:
        python-version: ['3.10']
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install conan
      uses: turtlebrowser/get-conan@v1.2
    - name: Set up conan
      run: |
        conan profile detect
        DEFAULT_PROFILE_PATH=`conan profile path default`
        PROFILE_PATH=./conan-profiles/macos-14
        diff ${DEFAULT_PROFILE_PATH} ${PROFILE_PATH} || true
        cp ${PROFILE_PATH} ${DEFAULT_PROFILE_PATH}
        conan remote add tket-libs https://quantinuumsw.jfrog.io/artifactory/api/conan/tket1-libs --index 0
    - name: Build tket C++
      env:
        MACOSX_DEPLOYMENT_TARGET: '12.0'
      run: conan create tket --user tket --channel stable --build=missing -o boost/*:header_only=True -o tklog/*:shared=True -o tket/*:shared=True -tf ""
    - name: Build wheel
      env:
        MACOSX_DEPLOYMENT_TARGET: '12.0'
      run: |
        conan create recipes/pybind11
        conan create recipes/pybind11_json/all --version 0.2.13
        cd pytket
        # Ensure wheels are compatible with MacOS 12.0 and later:
        export WHEEL_PLAT_NAME=macosx_12_0_arm64
        python${{ matrix.python-version }} -m pip install -U pip build delocate
        python${{ matrix.python-version }} -m build
        delocate-wheel -vv -w "$GITHUB_WORKSPACE/wheelhouse/" "dist/pytket-"*".whl"
    - uses: actions/upload-artifact@v4
      with:
        name: MacOS_arm64_${{ matrix.python-version }}_wheel
        path: wheelhouse/

  test_macos_arm64_wheels:
    name: Test macos arm64 wheels
    needs: build_macos_arm64_wheels
    strategy:
      matrix:
        os: ['macos-13-xlarge']
        python-version: ['3.10']
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Download wheels
      uses: actions/download-artifact@v4
      with:
        name: MacOS_arm64_${{ matrix.python-version }}_wheel
        path: wheelhouse/
    - uses: actions/checkout@v4
      with:
        path: tket
    - name: Install wheel
      run: |
        python${{ matrix.python-version }} -m pip install $GITHUB_WORKSPACE/wheelhouse/pytket-*.whl
    - name: Run tests
      run: |
        cd tket/pytket/tests
        python${{ matrix.python-version }} -m pip install -r requirements.txt
        python${{ matrix.python-version }} -m pytest --ignore=simulator/
